# Generated by Django 4.0.1 on 2022-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_created_at_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', to='api.Tag'),
        ),
    ]
