# Generated by Django 4.0.1 on 2022-08-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='me',
            field=models.CharField(default='me', max_length=15),
        ),
    ]
