# Generated by Django 4.0.1 on 2022-08-20 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tag_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='me',
        ),
    ]
