# Generated by Django 4.0.1 on 2022-08-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='comment_reply',
            name='status',
        ),
    ]
